[workspace]
authors = ["YU Zhejian <yuzj25@seas.upenn.edu>"]
channels = ["conda-forge"]
name = "slim_profiler"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[environments]
gpu-stress = { features = ["gpu-stress"] }
build = { features = ["build"] }
fmt = { features = ["fmt"] , no-default-feature = true }

[dependencies]
python = "3.12.*"
psutil = ">=7.2.2,<8"
pandas = ">=3.0.1,<4"
numpy = ">=2.4.2,<3"
matplotlib-base = ">=3.10.8,<4"

[feature.gpu-stress]
system-requirements = { cuda = "12.0" }

[feature.gpu-stress.dependencies]
nvidia-ml-py = "==13.590.48"
cuda-version = "12.6.*"
pytorch-gpu = "*"

[feature.build.dependencies]
python-build = "*"
twine = "*"

[feature.fmt.dependencies]
black = "*"

