# Some names were specified in pyproject.toml.
[workspace]
channels = ["conda-forge"]
name = "slim_profiler"
platforms = ["linux-64"]

[tasks]

[environments]
gpu-stress = { features = ["gpu-stress"] }
build = { features = ["build"] }
fmt = { features = ["fmt"] , no-default-feature = true }

[dependencies]
python = "3.10.*"
psutil = ">=7.2.2,<8"
pandas = ">=2.3.3,<3"
numpy = ">=2.2.6,<3"
matplotlib-base = ">=3.10.9,<4"

[feature.gpu-stress]
system-requirements = { cuda = "12.0" }

[feature.gpu-stress.dependencies]
nvidia-ml-py = ">=13.595.45,<14"
cuda-version = ">=12.9,<13"
pytorch-gpu = ">=2.10.0,<3"

[feature.build.dependencies]
python-build = ">=1.5.0,<2"
twine = ">=6.2.0,<7"

[feature.fmt.dependencies]
black = ">=26.5.1,<27"
